package com.nikolay.onlinediary.web;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.nikolay.onlinediary.dto.ContactForm;
import com.nikolay.onlinediary.repository.ContactRepository;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.test.web.servlet.MockMvc;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@ActiveProfiles("test")
@SpringBootTest
@AutoConfigureMockMvc(addFilters = false)
@Sql(statements = {
        "DROP TABLE IF EXISTS contacts",
        "CREATE TABLE contacts (" +
                "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                "first_name VARCHAR(255) NOT NULL," +
                "last_name VARCHAR(255) NOT NULL," +
                "email VARCHAR(255) NOT NULL UNIQUE," +
                "phone VARCHAR(50) NOT NULL UNIQUE)",
        "INSERT INTO contacts (first_name, last_name, email, phone) VALUES " +
                "('Ivan', 'Ivanov', 'ivan@example.com', '+7001')," +
                "('Petr', 'Petrov', 'petr@example.com', '+7002')"
}, executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD)
@Sql(statements = "DROP TABLE IF EXISTS contacts", executionPhase = Sql.ExecutionPhase.AFTER_TEST_METHOD)
class ContactRestIntegrationTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @Autowired
    private ContactRepository contactRepository;

    @Test
    void getAllReadsFromDatabase() throws Exception {
        mockMvc.perform(get("/api/contacts"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.length()").value(2))
                .andExpect(jsonPath("$[0].email").value("ivan@example.com"))
                .andExpect(jsonPath("$[1].phone").value("+7002"));
    }

    @Test
    void createPersistsContactAndPreventsDuplicates() throws Exception {
        ContactForm request = new ContactForm();
        request.setFirstName("New");
        request.setLastName("User");
        request.setEmail("new@example.com");
        request.setPhone("+7999");

        mockMvc.perform(post("/api/contacts")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isCreated());

        assertThat(contactRepository.findAll()).hasSize(3);

        mockMvc.perform(post("/api/contacts")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isConflict());
    }

    @Test
    void missingContactReturns404() throws Exception {
        mockMvc.perform(get("/api/contacts/999"))
                .andExpect(status().isNotFound());
    }
}
