CREATE TABLE users (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR2(255) NOT NULL,
    email        VARCHAR2(255) NOT NULL UNIQUE,
    password_hash VARCHAR2(255) NOT NULL,
    role         VARCHAR2(64) NOT NULL
);

CREATE TABLE contacts (
    id         NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(255) NOT NULL,
    last_name  VARCHAR2(255) NOT NULL,
    email      VARCHAR2(255) NOT NULL UNIQUE,
    phone      VARCHAR2(50)  NOT NULL UNIQUE
);

CREATE TABLE subjects (
    id          NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(255) NOT NULL,
    description VARCHAR2(500)
);

CREATE TABLE groups (
    id     NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name   VARCHAR2(255) NOT NULL,
    course NUMBER(10)
);

CREATE TABLE students (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    email VARCHAR2(255) NOT NULL UNIQUE
);

CREATE TABLE courses (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    student_id NUMBER(19,0) NOT NULL,
    CONSTRAINT fk_course_student FOREIGN KEY (student_id) REFERENCES students(id)
);

CREATE TABLE submissions (
    id           NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id   NUMBER(19,0) NOT NULL,
    subject_id   NUMBER(19,0) NOT NULL,
    content      CLOB,
    submitted_at TIMESTAMP
);

CREATE TABLE assessments (
    id NUMBER(19,0) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id NUMBER(19,0) NOT NULL,
    teacher_id NUMBER(19,0) NOT NULL,
    grade NUMBER(10) NOT NULL,
    commentText VARCHAR2(500),
    assessed_at TIMESTAMP,
    CONSTRAINT fk_assessment_submission FOREIGN KEY (submission_id) REFERENCES submissions(id)
);
